/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "crc.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

void test_crc16_ccitt(void)
{
  TEST_ASSERT_EQUAL_HEX16(0x3A18, crc16_ccitt("Hello"));
}

void test_crc16_byte_process(void)
{
  TEST_ASSERT_EQUAL_HEX16(0x8F58, crc16_byte_process((uint8_t)('A')));
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("crc.c");
  RUN_TEST(test_crc16_ccitt);
  RUN_TEST(test_crc16_byte_process);

  return UNITY_END();
}
